### ISSUE TITLE
isFilterable not working with the API integration

### ISSUE THREAD

**Issue by pullelakalyani** [imballinst/react-bs-datatable#129]
Hello @imballinst ,

I've tried with the same code with sample data that is present in the example sandbox it worked fine but when I integrated the API the filter functionality haven't worked. I got the following error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'isFilterable')`

With the sample data there is a Boolean flag as isFilterable which is set to true in the header coulumns and it worked with the sample data but when integrated with the API it throws an error

Any suggestions would be great

Thank you

**Comment by imballinst** [comment]
hi @pullelakalyani, thanks for using this library! I think I have found the root issue. I'll work on it.

**Comment by imballinst** [comment]
@pullelakalyani could you check with the newest update, `v3.2.1`? Previously it was a bug because I iterated all keys of the rows instead of the `prop` fields from the headers.

To test it, I put an unused field here in the story data: https://github.com/imballinst/react-bs-datatable/blob/main/src/__stories__/resources/story-data.json. As we can test here https://imballinst.github.io/react-bs-datatable/?path=/story/uncontrolled--filter-sort-pagination, it is still working properly, as does the unit tests.

Let me know if you still face further issues. Thanks!

**Comment by pullelakalyani** [comment]
Thankyou so much for the quick response @imballinst 
v3.2.1 worked for me !
