### ISSUE TITLE
Table does not sort when child is returned in <TableBody>

### ISSUE THREAD

**Issue by isabellachen** [imballinst/react-bs-datatable#154]
I was playing around with this [code sandbox](https://codesandbox.io/s/brave-silence-tp0d5j?file=/src/App.js) from another closed issue here, trying to get the rows to sort, but no success.

It was working in version 3.3.1 but is no longer working in later versions. 

The problem is when TableBody returns the TableRow instead of directly calling <TableBody />

```js
            <TableBody>
              {dataTableBody.map((row) => {
                return <TableRow key={row.case_id} rowData={row} />;
              })}
            </TableBody>
```

**Comment by imballinst** [comment]
Hey @isabellachen! Thanks for reporting this issue with sufficient description, I'll see what I can do.

**Comment by imballinst** [comment]
hi @isabellachen, according to the [API reference](https://github.com/imballinst/react-bs-datatable/blob/main/api/interfaces/components_TableBody.TableBodyProps.md#children), where this is the source:

https://github.com/imballinst/react-bs-datatable/blob/0e2d53065055cf8ed211226b0c133a9124f2dcf0/src/components/TableBody.tsx#L69-L72

I think the children now should be a function rather than JSX elements. Something like this: https://codesandbox.io/s/dry-firefly-g9s8v1?file=/src/App.js.

```jsx
<TableBody>
  {rows => {
    return rows.map((row) => {
      return <TableRow key={row.case_id} rowData={row} />;
    })
  }}
</TableBody>
```

Probably it works in 3.3.1 because back in 3.3.1, `TableBody` doesn't accept `children` prop, so it renders the table properly 🤔 

https://github.com/imballinst/react-bs-datatable/blob/f454c139cb245be8345201ea7b6673da2a30ee27/src/components/TableBody.tsx#L43-L67

Please let me know if you need further assistance. Thanks!

**Comment by isabellachen** [comment]
That was it. Thank you so much for the quick response!

**Comment by imballinst** [comment]
You are welcome @isabellachen! Thanks a lot for the sponsor, means a lot to me! 🙇‍♂️
