### ISSUE TITLE
Cannot re-render?

### ISSUE THREAD

**Issue by ans-4175** [Imballinst/react-bs-datatable#2]
Looking through https://imballinst.github.io/react-bs-datatable/
I put search text and changed number show options per page.
But it won't rendered, any misconfig on your gh-pages ?

**Comment by Imballinst** [comment]
Hi there!

I'm sorry I couldn't reproduce your problem with Chrome 55.0.2 and Firefox 50.1. I think, if the table doesn't render any row, your search text doesn't find any matching column in the given dataset. Could you give the steps to reproduce it and if possible, the screenshot as well, so I can analyze it further? Thanks

**Comment by ans-4175** [comment]
Changed to third page
![screenshot from 2017-01-25 08 39 40](https://cloud.githubusercontent.com/assets/3961872/22274572/dab74556-e2d9-11e6-98bd-4622c21f26a2.png)

Then search `brandy`, nothing result.
![screenshot from 2017-01-25 08 40 20](https://cloud.githubusercontent.com/assets/3961872/22274583/eef194fe-e2d9-11e6-8a2b-8692132ab4cb.png)

Looks like searching only works in first page?

**Comment by Imballinst** [comment]
You're right, there's a pagination problem when filtering on the pages other than the first one. My guess is that when the user filters the data, the "current pagination before filter" persists. 

1. User A switches to page 3 (page state on the table set to 3)
2. User A enters a text to the input field
3. This causes the entire dataset to be filtered based on A's input. Therefore, the table that once has N pages will now have less than N pages
4. If N <= 3, the component is still working. However, if N < 3, it will cause rendering problem because the component's state tells the render method to render the 3rd page, which is undefined after the filter.

Thanks for your report, I will address this issue soon.

**Comment by Imballinst** [comment]
@ans-4175 Hi, I just pushed a commit that should fix this issue. Please check the [Github Page of this repo](https://imballinst.github.io/react-bs-datatable/) to see whether this issue has been resolved or not

**Comment by ans-4175** [comment]
Still has a bug. If I put text to search, then only produced one result. I still can click next page button, so it will show empty results. Shouldn't be disabled the pagination button?

**Comment by Imballinst** [comment]
My bad, missed a logic on empty-dataset pagination. How is it [now](https://imballinst.github.io/react-bs-datatable)?

**Comment by ans-4175** [comment]
Good, works perfectly :)
