### ISSUE TITLE
Data is not coming when try to extend the table

### ISSUE THREAD

**Issue by RanjithaRaja** [Imballinst/react-bs-datatable#24]
Basic Datatable is working perfectly, but when try to extend the table data is not coming to the table body and pagination is also not working.

**Comment by Imballinst** [comment]
Sorry! Apparently I messed up the README and missed a little bit information on it.

I've updated the README: https://github.com/Imballinst/react-bs-datatable/commit/b93b89b0d4f4f67782710366dc9191e8e80962c0?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8. The misinformation lies here:

![image](https://user-images.githubusercontent.com/7077157/56188402-c33e0e00-6068-11e9-8016-3a2b8e123513.png)

I didn't get `onFilter` and pass it to the 3rd option of `filterData`. So, that's why. If you're having trouble with extending, I've prepared a working CodeSandbox demo: https://codesandbox.io/s/n59wzmw0zm

Please let me know if this fixes your issue @RanjithaRaja

**Comment by RanjithaRaja** [comment]
@Imballinst Thank you so much...It's working perfectly

**Comment by Imballinst** [comment]
No worries, I'm glad to help! :smile:

**Comment by RanjithaRaja** [comment]
@Imballinst filterPlaceholder property is not working while extending the table. But it's working in a Basic data table.
