### ISSUE TITLE
Mobile First Support for top panel

### ISSUE THREAD

**Issue by mmizera** [imballinst/react-bs-datatable#82]
Hi

Can you please add some css for top panel, so it stacks on lover resolutions ?

![mobile-not-first](https://user-images.githubusercontent.com/3079638/107541098-10d52480-6bc7-11eb-8024-7fef0d7f9f25.PNG)

**Comment by imballinst** [comment]
Hi @mmizera! Apologies for a very-very-very late reply! This should be fixed in the next major release (v3). Sample demo can be seen here: https://codesandbox.io/s/react-bs-datatable-3-zq7xe

![image](https://user-images.githubusercontent.com/7077157/151646624-b4839553-62b3-4bcb-a8cd-57e6ce6a200e.png)

![image](https://user-images.githubusercontent.com/7077157/151646627-593e3d17-cd77-4463-a831-3e945566b0b3.png)

![image](https://user-images.githubusercontent.com/7077157/151646628-5b964e5b-f7c4-4e34-a593-9de81774d651.png)

I'll try to backport it to v2 when I have the  chance. Let me know if you have other concerns!
