### ISSUE TITLE
How do I move the pagination to bottom of the table if I am not using storybook?

### ISSUE THREAD

**Issue by Gwachukwu** [imballinst/react-bs-datatable#93]

**Comment by imballinst** [comment]
@Gwachukwu hello! Here is the sandbox example to do it: https://codesandbox.io/s/extend-table-example-myv9b?file=/src/index.js

We don't need Storybook to move the pagination to bottom of the table. What we need is to compose our own table like this:

https://github.com/imballinst/react-bs-datatable/blob/757de71d5168e99b9699255c52722e5c3cebb9cf/src/__stories__/02-advanced/00-Extending.stories.js#L13-L128

What we are doing is that, instead of using `Datatable`, we are creating our own custom table with the components defined from the `Components` variable. After that, we can place our components wherever we want to. In this case, I am moving the pagination to the bottom right.

**Comment by Gwachukwu** [comment]
@imballinst Thank you. that was useful
