### ISSUE TITLE
filterable is not working

### ISSUE THREAD

**Issue by devrsingh1992** [imballinst/react-bs-datatable#95]
Hello team,

I have integrated datatable and it's working fine, except search filter, when i'm passing `filterable: true` , whole page showing white screen.

please help me to solve the problem.

**Comment by imballinst** [comment]
Hi @devrsingh1992! Sorry for a _very_ (even very might be an understatement)! If you are still interested in reporting this, could you share a bit of your code? A sample demo in https://codesandbox.io will be super helpful.

Thanks!

**Comment by ahmetunal** [comment]
Let me: https://codesandbox.io/s/react-bs-datatable-filterable-6vl6w

**Comment by imballinst** [comment]
> Let me: https://codesandbox.io/s/react-bs-datatable-filterable-6vl6w

thanks for the link! This is definitely a bug. I'll take a look.

**Comment by imballinst** [comment]
Update: this is because the used react-bootstrap is v2. I put the version of `react-bootstrap` in `peerDependencies` wrongly, so it didn't show a warning like this:

```
warning " > react-bs-datatable@2.2.1-alpha.0" has incorrect peer dependency "react-bootstrap@1.x".
```

Now, it will properly show that, and I will also add in the README that the v2 of this library will only be compatible to React Bootstrap v2 and Bootstrap v4.
